### ISSUE TITLE
How to set up path to the database SxGeoCity.dat?

### ISSUE THREAD

**Issue by sorbing** [likewinter/sypex-geo-laravel4#1]
Hi. I publish the config file:

```
php artisan config:publish likewinter/sypex-geo-laravel4
```

Setup him the path to the database `SxGeoCity.dat`..
But I still get the error: `Put database file in app\database\sypex`
Where you want to place the configuration file `sypexgeo`? Thanks.

**Comment by likewinter** [comment]
The db_path in config.php is path to file (ex. app/database/sypex/SxGeoCity.dat), not the path to folder with file. By the way: I do not plan to support this package anymore because Sypex switched to paid databases.
